server:
  http:
    addr: 0.0.0.0:8000
    timeout: 200s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 200s
  auth:
    jwks_url: "http://keycloak.go-mall.svc.cluster.local/realms/gomall/protocol/openid-connect/certs"
data:
  database:
    driver: postgres
    source: ""
