apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      labelSelector: "app in (catalog, cart, order, payment)"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/ports/-
        value:
          containerPort: 7000
          name: dlv
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe
      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe
      - op: add
        path: /spec/template/spec/containers/0/securityContext/capabilities
        value:
          add: ["SYS_PTRACE"]
