apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: greeter-debug-patch.yaml
    target:
      kind: Deployment
      name: greeter
  - path: greeter-svc-debug-patch.yaml
    target:
      kind: Service
      name: greeter
  - path: catalog-debug-patch.yaml
    target:
      kind: Deployment
      name: catalog
