Name: cart-api
Host: 0.0.0.0
Port: 8080

Log:
  Mode: console
  Level: info

DevServer:
  Port: 9012

Keycloak:
  RealmURL: "http://keycloak.go-mall.svc.cluster.local:8080/realms/go-mall"
  ClientID: "cart"
  ClientSecret: "cart-secret"
  JWKSCacheTTL: 24h

Telemetry:
  Name: cart-api
  Endpoint: http://jaeger.go-mall.svc.cluster.local:4318
  Sampler: 1.0
  Batcher: otlphttp

CatalogAppID: catalog-api
PaymentAppID: payment-api
