// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gomall/app/cart/internal/data/ent/cart"
	"gomall/app/cart/internal/data/ent/cartitem"
	"gomall/app/cart/internal/data/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cartFields := schema.Cart{}.Fields()
	_ = cartFields
	// cartDescSessionID is the schema descriptor for session_id field.
	cartDescSessionID := cartFields[1].Descriptor()
	// cart.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	cart.SessionIDValidator = cartDescSessionID.Validators[0].(func(string) error)
	// cartDescCreatedAt is the schema descriptor for created_at field.
	cartDescCreatedAt := cartFields[2].Descriptor()
	// cart.DefaultCreatedAt holds the default value on creation for the created_at field.
	cart.DefaultCreatedAt = cartDescCreatedAt.Default.(func() time.Time)
	// cartDescUpdatedAt is the schema descriptor for updated_at field.
	cartDescUpdatedAt := cartFields[3].Descriptor()
	// cart.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cart.DefaultUpdatedAt = cartDescUpdatedAt.Default.(func() time.Time)
	// cart.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cart.UpdateDefaultUpdatedAt = cartDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cartDescID is the schema descriptor for id field.
	cartDescID := cartFields[0].Descriptor()
	// cart.DefaultID holds the default value on creation for the id field.
	cart.DefaultID = cartDescID.Default.(func() uuid.UUID)
	cartitemFields := schema.CartItem{}.Fields()
	_ = cartitemFields
	// cartitemDescName is the schema descriptor for name field.
	cartitemDescName := cartitemFields[3].Descriptor()
	// cartitem.NameValidator is a validator for the "name" field. It is called by the builders before save.
	cartitem.NameValidator = cartitemDescName.Validators[0].(func(string) error)
	// cartitemDescPriceCents is the schema descriptor for price_cents field.
	cartitemDescPriceCents := cartitemFields[4].Descriptor()
	// cartitem.DefaultPriceCents holds the default value on creation for the price_cents field.
	cartitem.DefaultPriceCents = cartitemDescPriceCents.Default.(int64)
	// cartitemDescCurrency is the schema descriptor for currency field.
	cartitemDescCurrency := cartitemFields[5].Descriptor()
	// cartitem.DefaultCurrency holds the default value on creation for the currency field.
	cartitem.DefaultCurrency = cartitemDescCurrency.Default.(string)
	// cartitem.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	cartitem.CurrencyValidator = cartitemDescCurrency.Validators[0].(func(string) error)
	// cartitemDescQuantity is the schema descriptor for quantity field.
	cartitemDescQuantity := cartitemFields[7].Descriptor()
	// cartitem.DefaultQuantity holds the default value on creation for the quantity field.
	cartitem.DefaultQuantity = cartitemDescQuantity.Default.(int)
	// cartitemDescCreatedAt is the schema descriptor for created_at field.
	cartitemDescCreatedAt := cartitemFields[8].Descriptor()
	// cartitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	cartitem.DefaultCreatedAt = cartitemDescCreatedAt.Default.(func() time.Time)
	// cartitemDescUpdatedAt is the schema descriptor for updated_at field.
	cartitemDescUpdatedAt := cartitemFields[9].Descriptor()
	// cartitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cartitem.DefaultUpdatedAt = cartitemDescUpdatedAt.Default.(func() time.Time)
	// cartitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cartitem.UpdateDefaultUpdatedAt = cartitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cartitemDescID is the schema descriptor for id field.
	cartitemDescID := cartitemFields[0].Descriptor()
	// cartitem.DefaultID holds the default value on creation for the id field.
	cartitem.DefaultID = cartitemDescID.Default.(func() uuid.UUID)
}
