// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gomall/app/payment/internal/biz"
	"gomall/app/payment/internal/conf"
	"gomall/app/payment/internal/data"
	"gomall/app/payment/internal/server"
	"gomall/app/payment/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	paymentRepo := data.NewPaymentRepo(dataData, logger)
	paymentUsecase := biz.NewPaymentUsecase(paymentRepo)
	paymentService := service.NewPaymentService(paymentUsecase)
	grpcServer := server.NewGRPCServer(confServer, paymentService, logger)
	httpServer := server.NewHTTPServer(confServer, paymentService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
