apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image.registry }}/{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.auth.adminUser | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.auth.adminPassword | quote }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
