apiVersion: v1
kind: Service
metadata:
  name: greeter
spec:
  ports:
    - name: http
      port: 8000
    - name: grpc
      port: 9000
  selector:
    app: greeter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "greeter"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: greeter
          image: greeter
          ports:
            - containerPort: 8000
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /data/conf
      volumes:
        - name: config
          configMap:
            name: greeter-config
