apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-mall
resources:
  - namespace.yaml
  - infra
  - services
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: go-mall
      app.kubernetes.io/managed-by: kustomize
