// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CartItem is the predicate function for cartitem builders.
type CartItem func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OutboxMessage is the predicate function for outboxmessage builders.
type OutboxMessage func(*sql.Selector)
