// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

import (
	"time"

	"github.com/google/uuid"
)

type CreateProductRequest struct {
	Name        string  `json:"name"`
	Description string  `json:"description,optional"`
	Price       float64 `json:"price"`
	TotalStock  int64   `json:"totalStock"`
	CategoryId  int64   `json:"categoryId"`
}

type CreateProductResponse struct {
	Id uuid.UUID `json:"id"`
}

type DeleteProductRequest struct {
	Id uuid.UUID `path:"id"`
}

type GetProductRequest struct {
	Id uuid.UUID `path:"id"`
}

type ListProductRequest struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Keyword  string `form:"keyword,optional"`
}

type ListProductResponse struct {
	Total    int64         `json:"total"`
	Products []ProductInfo `json:"products"`
}

type ProductInfo struct {
	Id             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	Price          float64    `json:"price"`
	TotalStock     int64      `json:"totalStock"`
	RemainingStock int64      `json:"remainingStock"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      *time.Time `json:"updatedAt"`
}

type UpdateProductRequest struct {
	Id          uuid.UUID `path:"id"`
	Name        string    `json:"name,optional"`
	Description string    `json:"description,optional"`
	Price       float64   `json:"price,optional"`
}

type IncreaseProductStockRequest struct {
	Id       uuid.UUID `path:"id"`
	Quantity int64     `json:"quantity"`
}

type IncreaseProductStockResponse struct {
	Id uuid.UUID `json:"id"`
}
