// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cart/ent/cartitem"
	"cart/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CartItemUpdate is the builder for updating CartItem entities.
type CartItemUpdate struct {
	config
	hooks    []Hook
	mutation *CartItemMutation
}

// Where appends a list predicates to the CartItemUpdate builder.
func (_u *CartItemUpdate) Where(ps ...predicate.CartItem) *CartItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CartItemUpdate) SetUpdatedAt(v time.Time) *CartItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *CartItemUpdate) ClearUpdatedAt() *CartItemUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *CartItemUpdate) SetSessionID(v string) *CartItemUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *CartItemUpdate) SetNillableSessionID(v *string) *CartItemUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CartItemUpdate) SetProductID(v uuid.UUID) *CartItemUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CartItemUpdate) SetNillableProductID(v *uuid.UUID) *CartItemUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *CartItemUpdate) SetQuantity(v int64) *CartItemUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *CartItemUpdate) SetNillableQuantity(v *int64) *CartItemUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *CartItemUpdate) AddQuantity(v int64) *CartItemUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// Mutation returns the CartItemMutation object of the builder.
func (_u *CartItemUpdate) Mutation() *CartItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CartItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CartItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CartItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CartItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CartItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := cartitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CartItemUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := cartitem.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "CartItem.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quantity(); ok {
		if err := cartitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "CartItem.quantity": %w`, err)}
		}
	}
	return nil
}

func (_u *CartItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cartitem.Table, cartitem.Columns, sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cartitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(cartitem.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(cartitem.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(cartitem.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(cartitem.FieldQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(cartitem.FieldQuantity, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cartitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CartItemUpdateOne is the builder for updating a single CartItem entity.
type CartItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CartItemMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CartItemUpdateOne) SetUpdatedAt(v time.Time) *CartItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *CartItemUpdateOne) ClearUpdatedAt() *CartItemUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *CartItemUpdateOne) SetSessionID(v string) *CartItemUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *CartItemUpdateOne) SetNillableSessionID(v *string) *CartItemUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CartItemUpdateOne) SetProductID(v uuid.UUID) *CartItemUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CartItemUpdateOne) SetNillableProductID(v *uuid.UUID) *CartItemUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *CartItemUpdateOne) SetQuantity(v int64) *CartItemUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *CartItemUpdateOne) SetNillableQuantity(v *int64) *CartItemUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *CartItemUpdateOne) AddQuantity(v int64) *CartItemUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// Mutation returns the CartItemMutation object of the builder.
func (_u *CartItemUpdateOne) Mutation() *CartItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the CartItemUpdate builder.
func (_u *CartItemUpdateOne) Where(ps ...predicate.CartItem) *CartItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CartItemUpdateOne) Select(field string, fields ...string) *CartItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CartItem entity.
func (_u *CartItemUpdateOne) Save(ctx context.Context) (*CartItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CartItemUpdateOne) SaveX(ctx context.Context) *CartItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CartItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CartItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CartItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := cartitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CartItemUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := cartitem.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "CartItem.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quantity(); ok {
		if err := cartitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "CartItem.quantity": %w`, err)}
		}
	}
	return nil
}

func (_u *CartItemUpdateOne) sqlSave(ctx context.Context) (_node *CartItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cartitem.Table, cartitem.Columns, sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CartItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cartitem.FieldID)
		for _, f := range fields {
			if !cartitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cartitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cartitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(cartitem.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(cartitem.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(cartitem.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(cartitem.FieldQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(cartitem.FieldQuantity, field.TypeInt64, value)
	}
	_node = &CartItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cartitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
