// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cart/ent/outboxmessage"
	"encoding/json"
	"fmt"
	"shared/event"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// OutboxMessage is the model entity for the OutboxMessage schema.
type OutboxMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// EventName holds the value of the "event_name" field.
	EventName string `json:"event_name,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload json.RawMessage `json:"payload,omitempty"`
	// RetryAttempts holds the value of the "retry_attempts" field.
	RetryAttempts int32 `json:"retry_attempts,omitempty"`
	// Status holds the value of the "status" field.
	Status event.MessageStatus `json:"status,omitempty"`
	// SentAt holds the value of the "sent_at" field.
	SentAt       time.Time `json:"sent_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OutboxMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outboxmessage.FieldPayload:
			values[i] = new([]byte)
		case outboxmessage.FieldRetryAttempts:
			values[i] = new(sql.NullInt64)
		case outboxmessage.FieldEventName, outboxmessage.FieldStatus:
			values[i] = new(sql.NullString)
		case outboxmessage.FieldCreatedAt, outboxmessage.FieldUpdatedAt, outboxmessage.FieldSentAt:
			values[i] = new(sql.NullTime)
		case outboxmessage.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OutboxMessage fields.
func (_m *OutboxMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outboxmessage.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case outboxmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case outboxmessage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case outboxmessage.FieldEventName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_name", values[i])
			} else if value.Valid {
				_m.EventName = value.String
			}
		case outboxmessage.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case outboxmessage.FieldRetryAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_attempts", values[i])
			} else if value.Valid {
				_m.RetryAttempts = int32(value.Int64)
			}
		case outboxmessage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = event.MessageStatus(value.String)
			}
		case outboxmessage.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OutboxMessage.
// This includes values selected through modifiers, order, etc.
func (_m *OutboxMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OutboxMessage.
// Note that you need to call OutboxMessage.Unwrap() before calling this method if this OutboxMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OutboxMessage) Update() *OutboxMessageUpdateOne {
	return NewOutboxMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OutboxMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OutboxMessage) Unwrap() *OutboxMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OutboxMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OutboxMessage) String() string {
	var builder strings.Builder
	builder.WriteString("OutboxMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("event_name=")
	builder.WriteString(_m.EventName)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("retry_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryAttempts))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("sent_at=")
	builder.WriteString(_m.SentAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OutboxMessages is a parsable slice of OutboxMessage.
type OutboxMessages []*OutboxMessage
