// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cart/ent/cartitem"
	"cart/ent/outboxmessage"
	"cart/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cartitemMixin := schema.CartItem{}.Mixin()
	cartitemMixinFields0 := cartitemMixin[0].Fields()
	_ = cartitemMixinFields0
	cartitemMixinFields1 := cartitemMixin[1].Fields()
	_ = cartitemMixinFields1
	cartitemFields := schema.CartItem{}.Fields()
	_ = cartitemFields
	// cartitemDescCreatedAt is the schema descriptor for created_at field.
	cartitemDescCreatedAt := cartitemMixinFields1[0].Descriptor()
	// cartitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	cartitem.DefaultCreatedAt = cartitemDescCreatedAt.Default.(func() time.Time)
	// cartitemDescUpdatedAt is the schema descriptor for updated_at field.
	cartitemDescUpdatedAt := cartitemMixinFields1[1].Descriptor()
	// cartitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cartitem.UpdateDefaultUpdatedAt = cartitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cartitemDescSessionID is the schema descriptor for session_id field.
	cartitemDescSessionID := cartitemFields[0].Descriptor()
	// cartitem.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	cartitem.SessionIDValidator = cartitemDescSessionID.Validators[0].(func(string) error)
	// cartitemDescQuantity is the schema descriptor for quantity field.
	cartitemDescQuantity := cartitemFields[2].Descriptor()
	// cartitem.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	cartitem.QuantityValidator = cartitemDescQuantity.Validators[0].(func(int64) error)
	// cartitemDescID is the schema descriptor for id field.
	cartitemDescID := cartitemMixinFields0[0].Descriptor()
	// cartitem.DefaultID holds the default value on creation for the id field.
	cartitem.DefaultID = cartitemDescID.Default.(func() uuid.UUID)
	outboxmessageMixin := schema.OutboxMessage{}.Mixin()
	outboxmessageMixinFields0 := outboxmessageMixin[0].Fields()
	_ = outboxmessageMixinFields0
	outboxmessageMixinFields1 := outboxmessageMixin[1].Fields()
	_ = outboxmessageMixinFields1
	outboxmessageMixinFields2 := outboxmessageMixin[2].Fields()
	_ = outboxmessageMixinFields2
	outboxmessageFields := schema.OutboxMessage{}.Fields()
	_ = outboxmessageFields
	// outboxmessageDescCreatedAt is the schema descriptor for created_at field.
	outboxmessageDescCreatedAt := outboxmessageMixinFields1[0].Descriptor()
	// outboxmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	outboxmessage.DefaultCreatedAt = outboxmessageDescCreatedAt.Default.(func() time.Time)
	// outboxmessageDescUpdatedAt is the schema descriptor for updated_at field.
	outboxmessageDescUpdatedAt := outboxmessageMixinFields1[1].Descriptor()
	// outboxmessage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	outboxmessage.UpdateDefaultUpdatedAt = outboxmessageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// outboxmessageDescRetryAttempts is the schema descriptor for retry_attempts field.
	outboxmessageDescRetryAttempts := outboxmessageMixinFields2[2].Descriptor()
	// outboxmessage.DefaultRetryAttempts holds the default value on creation for the retry_attempts field.
	outboxmessage.DefaultRetryAttempts = outboxmessageDescRetryAttempts.Default.(int32)
	// outboxmessageDescID is the schema descriptor for id field.
	outboxmessageDescID := outboxmessageMixinFields0[0].Descriptor()
	// outboxmessage.DefaultID holds the default value on creation for the id field.
	outboxmessage.DefaultID = outboxmessageDescID.Default.(func() uuid.UUID)
}
