// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PaymentsColumns holds the columns for the "payments" table.
	PaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "order_id", Type: field.TypeString, Size: 128},
		{Name: "user_id", Type: field.TypeString, Size: 128},
		{Name: "amount_cents", Type: field.TypeInt64, Default: 0},
		{Name: "currency", Type: field.TypeString, Size: 3, Default: "USD"},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "PENDING"},
		{Name: "provider", Type: field.TypeString, Size: 64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PaymentsTable holds the schema information for the "payments" table.
	PaymentsTable = &schema.Table{
		Name:       "payments",
		Columns:    PaymentsColumns,
		PrimaryKey: []*schema.Column{PaymentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "payment_order_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentsColumns[1]},
			},
			{
				Name:    "payment_user_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PaymentsTable,
	}
)

func init() {
}
