apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - catalog-api/catalog.yaml
  - cart-api/cart.yaml
  - payment-api/payment.yaml
  - storefront.yaml

configMapGenerator:
  - name: catalog-config
    files:
      - catalog-api.yaml=catalog-api/config.yaml
  - name: cart-config
    files:
      - cart-api.yaml=cart-api/config.yaml
  - name: payment-config
    files:
      - payment-api.yaml=payment-api/config.yaml
