// Code generated by ent, DO NOT EDIT.

package ent

import (
	"catalog/ent/predicate"
	"catalog/ent/reservation"
	"catalog/ent/schema"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ReservationUpdate is the builder for updating Reservation entities.
type ReservationUpdate struct {
	config
	hooks    []Hook
	mutation *ReservationMutation
}

// Where appends a list predicates to the ReservationUpdate builder.
func (_u *ReservationUpdate) Where(ps ...predicate.Reservation) *ReservationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReservationUpdate) SetUpdatedAt(v time.Time) *ReservationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ReservationUpdate) ClearUpdatedAt() *ReservationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ReservationUpdate) SetSessionID(v string) *ReservationUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ReservationUpdate) SetNillableSessionID(v *string) *ReservationUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReservationUpdate) SetStatus(v string) *ReservationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReservationUpdate) SetNillableStatus(v *string) *ReservationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetItems sets the "items" field.
func (_u *ReservationUpdate) SetItems(v []schema.ReservationItem) *ReservationUpdate {
	_u.mutation.SetItems(v)
	return _u
}

// AppendItems appends value to the "items" field.
func (_u *ReservationUpdate) AppendItems(v []schema.ReservationItem) *ReservationUpdate {
	_u.mutation.AppendItems(v)
	return _u
}

// Mutation returns the ReservationMutation object of the builder.
func (_u *ReservationUpdate) Mutation() *ReservationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReservationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReservationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReservationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReservationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReservationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := reservation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReservationUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := reservation.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Reservation.session_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ReservationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reservation.Table, reservation.Columns, sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(reservation.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(reservation.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reservation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Items(); ok {
		_spec.SetField(reservation.FieldItems, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedItems(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, reservation.FieldItems, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReservationUpdateOne is the builder for updating a single Reservation entity.
type ReservationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReservationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReservationUpdateOne) SetUpdatedAt(v time.Time) *ReservationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ReservationUpdateOne) ClearUpdatedAt() *ReservationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ReservationUpdateOne) SetSessionID(v string) *ReservationUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ReservationUpdateOne) SetNillableSessionID(v *string) *ReservationUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReservationUpdateOne) SetStatus(v string) *ReservationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReservationUpdateOne) SetNillableStatus(v *string) *ReservationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetItems sets the "items" field.
func (_u *ReservationUpdateOne) SetItems(v []schema.ReservationItem) *ReservationUpdateOne {
	_u.mutation.SetItems(v)
	return _u
}

// AppendItems appends value to the "items" field.
func (_u *ReservationUpdateOne) AppendItems(v []schema.ReservationItem) *ReservationUpdateOne {
	_u.mutation.AppendItems(v)
	return _u
}

// Mutation returns the ReservationMutation object of the builder.
func (_u *ReservationUpdateOne) Mutation() *ReservationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReservationUpdate builder.
func (_u *ReservationUpdateOne) Where(ps ...predicate.Reservation) *ReservationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReservationUpdateOne) Select(field string, fields ...string) *ReservationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Reservation entity.
func (_u *ReservationUpdateOne) Save(ctx context.Context) (*Reservation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReservationUpdateOne) SaveX(ctx context.Context) *Reservation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReservationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReservationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReservationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := reservation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReservationUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := reservation.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Reservation.session_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ReservationUpdateOne) sqlSave(ctx context.Context) (_node *Reservation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reservation.Table, reservation.Columns, sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Reservation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reservation.FieldID)
		for _, f := range fields {
			if !reservation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(reservation.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(reservation.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reservation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Items(); ok {
		_spec.SetField(reservation.FieldItems, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedItems(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, reservation.FieldItems, value)
		})
	}
	_node = &Reservation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
