// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CartsColumns holds the columns for the "carts" table.
	CartsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "session_id", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CartsTable holds the schema information for the "carts" table.
	CartsTable = &schema.Table{
		Name:       "carts",
		Columns:    CartsColumns,
		PrimaryKey: []*schema.Column{CartsColumns[0]},
	}
	// CartItemsColumns holds the columns for the "cart_items" table.
	CartItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "product_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 200},
		{Name: "price_cents", Type: field.TypeInt64, Default: 0},
		{Name: "currency", Type: field.TypeString, Size: 3, Default: "USD"},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "quantity", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "cart_id", Type: field.TypeUUID},
	}
	// CartItemsTable holds the schema information for the "cart_items" table.
	CartItemsTable = &schema.Table{
		Name:       "cart_items",
		Columns:    CartItemsColumns,
		PrimaryKey: []*schema.Column{CartItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cart_items_carts_items",
				Columns:    []*schema.Column{CartItemsColumns[9]},
				RefColumns: []*schema.Column{CartsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "cartitem_cart_id_product_id",
				Unique:  true,
				Columns: []*schema.Column{CartItemsColumns[9], CartItemsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CartsTable,
		CartItemsTable,
	}
)

func init() {
	CartItemsTable.ForeignKeys[0].RefTable = CartsTable
}
