// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"gomall/app/order/internal/data/ent/migrate"

	"gomall/app/order/internal/data/ent/idempotencykey"
	"gomall/app/order/internal/data/ent/order"
	"gomall/app/order/internal/data/ent/workflowdeadletterevent"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// IdempotencyKey is the client for interacting with the IdempotencyKey builders.
	IdempotencyKey *IdempotencyKeyClient
	// Order is the client for interacting with the Order builders.
	Order *OrderClient
	// WorkflowDeadLetterEvent is the client for interacting with the WorkflowDeadLetterEvent builders.
	WorkflowDeadLetterEvent *WorkflowDeadLetterEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.IdempotencyKey = NewIdempotencyKeyClient(c.config)
	c.Order = NewOrderClient(c.config)
	c.WorkflowDeadLetterEvent = NewWorkflowDeadLetterEventClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                     ctx,
		config:                  cfg,
		IdempotencyKey:          NewIdempotencyKeyClient(cfg),
		Order:                   NewOrderClient(cfg),
		WorkflowDeadLetterEvent: NewWorkflowDeadLetterEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                     ctx,
		config:                  cfg,
		IdempotencyKey:          NewIdempotencyKeyClient(cfg),
		Order:                   NewOrderClient(cfg),
		WorkflowDeadLetterEvent: NewWorkflowDeadLetterEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		IdempotencyKey.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.IdempotencyKey.Use(hooks...)
	c.Order.Use(hooks...)
	c.WorkflowDeadLetterEvent.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.IdempotencyKey.Intercept(interceptors...)
	c.Order.Intercept(interceptors...)
	c.WorkflowDeadLetterEvent.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *IdempotencyKeyMutation:
		return c.IdempotencyKey.mutate(ctx, m)
	case *OrderMutation:
		return c.Order.mutate(ctx, m)
	case *WorkflowDeadLetterEventMutation:
		return c.WorkflowDeadLetterEvent.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// IdempotencyKeyClient is a client for the IdempotencyKey schema.
type IdempotencyKeyClient struct {
	config
}

// NewIdempotencyKeyClient returns a client for the IdempotencyKey from the given config.
func NewIdempotencyKeyClient(c config) *IdempotencyKeyClient {
	return &IdempotencyKeyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `idempotencykey.Hooks(f(g(h())))`.
func (c *IdempotencyKeyClient) Use(hooks ...Hook) {
	c.hooks.IdempotencyKey = append(c.hooks.IdempotencyKey, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `idempotencykey.Intercept(f(g(h())))`.
func (c *IdempotencyKeyClient) Intercept(interceptors ...Interceptor) {
	c.inters.IdempotencyKey = append(c.inters.IdempotencyKey, interceptors...)
}

// Create returns a builder for creating a IdempotencyKey entity.
func (c *IdempotencyKeyClient) Create() *IdempotencyKeyCreate {
	mutation := newIdempotencyKeyMutation(c.config, OpCreate)
	return &IdempotencyKeyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of IdempotencyKey entities.
func (c *IdempotencyKeyClient) CreateBulk(builders ...*IdempotencyKeyCreate) *IdempotencyKeyCreateBulk {
	return &IdempotencyKeyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IdempotencyKeyClient) MapCreateBulk(slice any, setFunc func(*IdempotencyKeyCreate, int)) *IdempotencyKeyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IdempotencyKeyCreateBulk{err: fmt.Errorf("calling to IdempotencyKeyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IdempotencyKeyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IdempotencyKeyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for IdempotencyKey.
func (c *IdempotencyKeyClient) Update() *IdempotencyKeyUpdate {
	mutation := newIdempotencyKeyMutation(c.config, OpUpdate)
	return &IdempotencyKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IdempotencyKeyClient) UpdateOne(_m *IdempotencyKey) *IdempotencyKeyUpdateOne {
	mutation := newIdempotencyKeyMutation(c.config, OpUpdateOne, withIdempotencyKey(_m))
	return &IdempotencyKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IdempotencyKeyClient) UpdateOneID(id int) *IdempotencyKeyUpdateOne {
	mutation := newIdempotencyKeyMutation(c.config, OpUpdateOne, withIdempotencyKeyID(id))
	return &IdempotencyKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for IdempotencyKey.
func (c *IdempotencyKeyClient) Delete() *IdempotencyKeyDelete {
	mutation := newIdempotencyKeyMutation(c.config, OpDelete)
	return &IdempotencyKeyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IdempotencyKeyClient) DeleteOne(_m *IdempotencyKey) *IdempotencyKeyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IdempotencyKeyClient) DeleteOneID(id int) *IdempotencyKeyDeleteOne {
	builder := c.Delete().Where(idempotencykey.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IdempotencyKeyDeleteOne{builder}
}

// Query returns a query builder for IdempotencyKey.
func (c *IdempotencyKeyClient) Query() *IdempotencyKeyQuery {
	return &IdempotencyKeyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIdempotencyKey},
		inters: c.Interceptors(),
	}
}

// Get returns a IdempotencyKey entity by its id.
func (c *IdempotencyKeyClient) Get(ctx context.Context, id int) (*IdempotencyKey, error) {
	return c.Query().Where(idempotencykey.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IdempotencyKeyClient) GetX(ctx context.Context, id int) *IdempotencyKey {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *IdempotencyKeyClient) Hooks() []Hook {
	return c.hooks.IdempotencyKey
}

// Interceptors returns the client interceptors.
func (c *IdempotencyKeyClient) Interceptors() []Interceptor {
	return c.inters.IdempotencyKey
}

func (c *IdempotencyKeyClient) mutate(ctx context.Context, m *IdempotencyKeyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IdempotencyKeyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IdempotencyKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IdempotencyKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IdempotencyKeyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown IdempotencyKey mutation op: %q", m.Op())
	}
}

// OrderClient is a client for the Order schema.
type OrderClient struct {
	config
}

// NewOrderClient returns a client for the Order from the given config.
func NewOrderClient(c config) *OrderClient {
	return &OrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `order.Hooks(f(g(h())))`.
func (c *OrderClient) Use(hooks ...Hook) {
	c.hooks.Order = append(c.hooks.Order, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `order.Intercept(f(g(h())))`.
func (c *OrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.Order = append(c.inters.Order, interceptors...)
}

// Create returns a builder for creating a Order entity.
func (c *OrderClient) Create() *OrderCreate {
	mutation := newOrderMutation(c.config, OpCreate)
	return &OrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Order entities.
func (c *OrderClient) CreateBulk(builders ...*OrderCreate) *OrderCreateBulk {
	return &OrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrderClient) MapCreateBulk(slice any, setFunc func(*OrderCreate, int)) *OrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrderCreateBulk{err: fmt.Errorf("calling to OrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Order.
func (c *OrderClient) Update() *OrderUpdate {
	mutation := newOrderMutation(c.config, OpUpdate)
	return &OrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrderClient) UpdateOne(_m *Order) *OrderUpdateOne {
	mutation := newOrderMutation(c.config, OpUpdateOne, withOrder(_m))
	return &OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrderClient) UpdateOneID(id uuid.UUID) *OrderUpdateOne {
	mutation := newOrderMutation(c.config, OpUpdateOne, withOrderID(id))
	return &OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Order.
func (c *OrderClient) Delete() *OrderDelete {
	mutation := newOrderMutation(c.config, OpDelete)
	return &OrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrderClient) DeleteOne(_m *Order) *OrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrderClient) DeleteOneID(id uuid.UUID) *OrderDeleteOne {
	builder := c.Delete().Where(order.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrderDeleteOne{builder}
}

// Query returns a query builder for Order.
func (c *OrderClient) Query() *OrderQuery {
	return &OrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a Order entity by its id.
func (c *OrderClient) Get(ctx context.Context, id uuid.UUID) (*Order, error) {
	return c.Query().Where(order.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrderClient) GetX(ctx context.Context, id uuid.UUID) *Order {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OrderClient) Hooks() []Hook {
	return c.hooks.Order
}

// Interceptors returns the client interceptors.
func (c *OrderClient) Interceptors() []Interceptor {
	return c.inters.Order
}

func (c *OrderClient) mutate(ctx context.Context, m *OrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Order mutation op: %q", m.Op())
	}
}

// WorkflowDeadLetterEventClient is a client for the WorkflowDeadLetterEvent schema.
type WorkflowDeadLetterEventClient struct {
	config
}

// NewWorkflowDeadLetterEventClient returns a client for the WorkflowDeadLetterEvent from the given config.
func NewWorkflowDeadLetterEventClient(c config) *WorkflowDeadLetterEventClient {
	return &WorkflowDeadLetterEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `workflowdeadletterevent.Hooks(f(g(h())))`.
func (c *WorkflowDeadLetterEventClient) Use(hooks ...Hook) {
	c.hooks.WorkflowDeadLetterEvent = append(c.hooks.WorkflowDeadLetterEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `workflowdeadletterevent.Intercept(f(g(h())))`.
func (c *WorkflowDeadLetterEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.WorkflowDeadLetterEvent = append(c.inters.WorkflowDeadLetterEvent, interceptors...)
}

// Create returns a builder for creating a WorkflowDeadLetterEvent entity.
func (c *WorkflowDeadLetterEventClient) Create() *WorkflowDeadLetterEventCreate {
	mutation := newWorkflowDeadLetterEventMutation(c.config, OpCreate)
	return &WorkflowDeadLetterEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WorkflowDeadLetterEvent entities.
func (c *WorkflowDeadLetterEventClient) CreateBulk(builders ...*WorkflowDeadLetterEventCreate) *WorkflowDeadLetterEventCreateBulk {
	return &WorkflowDeadLetterEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WorkflowDeadLetterEventClient) MapCreateBulk(slice any, setFunc func(*WorkflowDeadLetterEventCreate, int)) *WorkflowDeadLetterEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WorkflowDeadLetterEventCreateBulk{err: fmt.Errorf("calling to WorkflowDeadLetterEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WorkflowDeadLetterEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WorkflowDeadLetterEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WorkflowDeadLetterEvent.
func (c *WorkflowDeadLetterEventClient) Update() *WorkflowDeadLetterEventUpdate {
	mutation := newWorkflowDeadLetterEventMutation(c.config, OpUpdate)
	return &WorkflowDeadLetterEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorkflowDeadLetterEventClient) UpdateOne(_m *WorkflowDeadLetterEvent) *WorkflowDeadLetterEventUpdateOne {
	mutation := newWorkflowDeadLetterEventMutation(c.config, OpUpdateOne, withWorkflowDeadLetterEvent(_m))
	return &WorkflowDeadLetterEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WorkflowDeadLetterEventClient) UpdateOneID(id uuid.UUID) *WorkflowDeadLetterEventUpdateOne {
	mutation := newWorkflowDeadLetterEventMutation(c.config, OpUpdateOne, withWorkflowDeadLetterEventID(id))
	return &WorkflowDeadLetterEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WorkflowDeadLetterEvent.
func (c *WorkflowDeadLetterEventClient) Delete() *WorkflowDeadLetterEventDelete {
	mutation := newWorkflowDeadLetterEventMutation(c.config, OpDelete)
	return &WorkflowDeadLetterEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WorkflowDeadLetterEventClient) DeleteOne(_m *WorkflowDeadLetterEvent) *WorkflowDeadLetterEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WorkflowDeadLetterEventClient) DeleteOneID(id uuid.UUID) *WorkflowDeadLetterEventDeleteOne {
	builder := c.Delete().Where(workflowdeadletterevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WorkflowDeadLetterEventDeleteOne{builder}
}

// Query returns a query builder for WorkflowDeadLetterEvent.
func (c *WorkflowDeadLetterEventClient) Query() *WorkflowDeadLetterEventQuery {
	return &WorkflowDeadLetterEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWorkflowDeadLetterEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a WorkflowDeadLetterEvent entity by its id.
func (c *WorkflowDeadLetterEventClient) Get(ctx context.Context, id uuid.UUID) (*WorkflowDeadLetterEvent, error) {
	return c.Query().Where(workflowdeadletterevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WorkflowDeadLetterEventClient) GetX(ctx context.Context, id uuid.UUID) *WorkflowDeadLetterEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WorkflowDeadLetterEventClient) Hooks() []Hook {
	return c.hooks.WorkflowDeadLetterEvent
}

// Interceptors returns the client interceptors.
func (c *WorkflowDeadLetterEventClient) Interceptors() []Interceptor {
	return c.inters.WorkflowDeadLetterEvent
}

func (c *WorkflowDeadLetterEventClient) mutate(ctx context.Context, m *WorkflowDeadLetterEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WorkflowDeadLetterEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WorkflowDeadLetterEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WorkflowDeadLetterEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WorkflowDeadLetterEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WorkflowDeadLetterEvent mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		IdempotencyKey, Order, WorkflowDeadLetterEvent []ent.Hook
	}
	inters struct {
		IdempotencyKey, Order, WorkflowDeadLetterEvent []ent.Interceptor
	}
)
