// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gomall/app/order/internal/data/ent/completedworkflow"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CompletedWorkflow is the model entity for the CompletedWorkflow schema.
type CompletedWorkflow struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// InstanceID holds the value of the "instance_id" field.
	InstanceID string `json:"instance_id,omitempty"`
	// TerminalState holds the value of the "terminal_state" field.
	TerminalState string `json:"terminal_state,omitempty"`
	// TerminatedAt holds the value of the "terminated_at" field.
	TerminatedAt time.Time `json:"terminated_at,omitempty"`
	// PurgedAt holds the value of the "purged_at" field.
	PurgedAt     *time.Time `json:"purged_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CompletedWorkflow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case completedworkflow.FieldID:
			values[i] = new(sql.NullInt64)
		case completedworkflow.FieldInstanceID, completedworkflow.FieldTerminalState:
			values[i] = new(sql.NullString)
		case completedworkflow.FieldTerminatedAt, completedworkflow.FieldPurgedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CompletedWorkflow fields.
func (_m *CompletedWorkflow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case completedworkflow.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case completedworkflow.FieldInstanceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field instance_id", values[i])
			} else if value.Valid {
				_m.InstanceID = value.String
			}
		case completedworkflow.FieldTerminalState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field terminal_state", values[i])
			} else if value.Valid {
				_m.TerminalState = value.String
			}
		case completedworkflow.FieldTerminatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field terminated_at", values[i])
			} else if value.Valid {
				_m.TerminatedAt = value.Time
			}
		case completedworkflow.FieldPurgedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field purged_at", values[i])
			} else if value.Valid {
				_m.PurgedAt = new(time.Time)
				*_m.PurgedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CompletedWorkflow.
// This includes values selected through modifiers, order, etc.
func (_m *CompletedWorkflow) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CompletedWorkflow.
// Note that you need to call CompletedWorkflow.Unwrap() before calling this method if this CompletedWorkflow
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CompletedWorkflow) Update() *CompletedWorkflowUpdateOne {
	return NewCompletedWorkflowClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CompletedWorkflow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CompletedWorkflow) Unwrap() *CompletedWorkflow {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CompletedWorkflow is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CompletedWorkflow) String() string {
	var builder strings.Builder
	builder.WriteString("CompletedWorkflow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("instance_id=")
	builder.WriteString(_m.InstanceID)
	builder.WriteString(", ")
	builder.WriteString("terminal_state=")
	builder.WriteString(_m.TerminalState)
	builder.WriteString(", ")
	builder.WriteString("terminated_at=")
	builder.WriteString(_m.TerminatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PurgedAt; v != nil {
		builder.WriteString("purged_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CompletedWorkflows is a parsable slice of CompletedWorkflow.
type CompletedWorkflows []*CompletedWorkflow
