// Code generated by ent, DO NOT EDIT.

package workflowdeadletterevent

import (
	"gomall/app/order/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLTE(FieldID, id))
}

// Topic applies equality check predicate on the "topic" field. It's identical to TopicEQ.
func Topic(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldTopic, v))
}

// PayloadJSON applies equality check predicate on the "payload_json" field. It's identical to PayloadJSONEQ.
func PayloadJSON(v []byte) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldPayloadJSON, v))
}

// WorkflowInstanceID applies equality check predicate on the "workflow_instance_id" field. It's identical to WorkflowInstanceIDEQ.
func WorkflowInstanceID(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldWorkflowInstanceID, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// TopicEQ applies the EQ predicate on the "topic" field.
func TopicEQ(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldTopic, v))
}

// TopicNEQ applies the NEQ predicate on the "topic" field.
func TopicNEQ(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNEQ(FieldTopic, v))
}

// TopicIn applies the In predicate on the "topic" field.
func TopicIn(vs ...string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldIn(FieldTopic, vs...))
}

// TopicNotIn applies the NotIn predicate on the "topic" field.
func TopicNotIn(vs ...string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNotIn(FieldTopic, vs...))
}

// TopicGT applies the GT predicate on the "topic" field.
func TopicGT(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGT(FieldTopic, v))
}

// TopicGTE applies the GTE predicate on the "topic" field.
func TopicGTE(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGTE(FieldTopic, v))
}

// TopicLT applies the LT predicate on the "topic" field.
func TopicLT(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLT(FieldTopic, v))
}

// TopicLTE applies the LTE predicate on the "topic" field.
func TopicLTE(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLTE(FieldTopic, v))
}

// TopicContains applies the Contains predicate on the "topic" field.
func TopicContains(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldContains(FieldTopic, v))
}

// TopicHasPrefix applies the HasPrefix predicate on the "topic" field.
func TopicHasPrefix(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldHasPrefix(FieldTopic, v))
}

// TopicHasSuffix applies the HasSuffix predicate on the "topic" field.
func TopicHasSuffix(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldHasSuffix(FieldTopic, v))
}

// TopicEqualFold applies the EqualFold predicate on the "topic" field.
func TopicEqualFold(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEqualFold(FieldTopic, v))
}

// TopicContainsFold applies the ContainsFold predicate on the "topic" field.
func TopicContainsFold(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldContainsFold(FieldTopic, v))
}

// PayloadJSONEQ applies the EQ predicate on the "payload_json" field.
func PayloadJSONEQ(v []byte) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldPayloadJSON, v))
}

// PayloadJSONNEQ applies the NEQ predicate on the "payload_json" field.
func PayloadJSONNEQ(v []byte) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNEQ(FieldPayloadJSON, v))
}

// PayloadJSONIn applies the In predicate on the "payload_json" field.
func PayloadJSONIn(vs ...[]byte) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldIn(FieldPayloadJSON, vs...))
}

// PayloadJSONNotIn applies the NotIn predicate on the "payload_json" field.
func PayloadJSONNotIn(vs ...[]byte) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNotIn(FieldPayloadJSON, vs...))
}

// PayloadJSONGT applies the GT predicate on the "payload_json" field.
func PayloadJSONGT(v []byte) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGT(FieldPayloadJSON, v))
}

// PayloadJSONGTE applies the GTE predicate on the "payload_json" field.
func PayloadJSONGTE(v []byte) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGTE(FieldPayloadJSON, v))
}

// PayloadJSONLT applies the LT predicate on the "payload_json" field.
func PayloadJSONLT(v []byte) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLT(FieldPayloadJSON, v))
}

// PayloadJSONLTE applies the LTE predicate on the "payload_json" field.
func PayloadJSONLTE(v []byte) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLTE(FieldPayloadJSON, v))
}

// WorkflowInstanceIDEQ applies the EQ predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDEQ(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDNEQ applies the NEQ predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDNEQ(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNEQ(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDIn applies the In predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDIn(vs ...string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldIn(FieldWorkflowInstanceID, vs...))
}

// WorkflowInstanceIDNotIn applies the NotIn predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDNotIn(vs ...string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNotIn(FieldWorkflowInstanceID, vs...))
}

// WorkflowInstanceIDGT applies the GT predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDGT(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGT(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDGTE applies the GTE predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDGTE(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGTE(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDLT applies the LT predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDLT(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLT(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDLTE applies the LTE predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDLTE(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLTE(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDContains applies the Contains predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDContains(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldContains(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDHasPrefix applies the HasPrefix predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDHasPrefix(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldHasPrefix(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDHasSuffix applies the HasSuffix predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDHasSuffix(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldHasSuffix(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDEqualFold applies the EqualFold predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDEqualFold(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEqualFold(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDContainsFold applies the ContainsFold predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDContainsFold(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldContainsFold(FieldWorkflowInstanceID, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldContainsFold(FieldReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowDeadLetterEvent) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowDeadLetterEvent) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowDeadLetterEvent) predicate.WorkflowDeadLetterEvent {
	return predicate.WorkflowDeadLetterEvent(sql.NotPredicates(p))
}
