Name: payment-api
Host: 0.0.0.0
Port: 8080

Log:
  Mode: console
  Level: info

DevServer:
  Port: 9013

Keycloak:
  RealmURL: "http://localhost:8080/realms/go-mall"
  ClientID: "payment"
  ClientSecret: ""
  JWKSCacheTTL: 24h

Telemetry:
  Name: payment-api
  Endpoint: http://localhost:4318
  Sampler: 1.0
  Batcher: otlphttp

