Name: catalog-api
Host: 0.0.0.0
Port: 8080

Log:
  Mode: console
  Level: info

DevServer:
  Port: 9011

Keycloak:
  RealmURL: "http://localhost:8080/realms/go-mall"
  ClientID: "catalog"
  ClientSecret: ""
  JWKSCacheTTL: 24h

Telemetry:
  Name: catalog-api
  Endpoint: http://localhost:4318
  Sampler: 1.0
  Batcher: otlphttp

DB:
  DSN: "postgres://postgres:gomall@localhost:5432/catalog?sslmode=disable"
