apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "payment-api"
        dapr.io/app-port: "8080"
        dapr.io/app-protocol: "http"
        dapr.io/config: "go-mall"
    spec:
      containers:
        - name: payment
          image: go-mall/payment
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /readyz
              port: 8080
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 20
            failureThreshold: 5
          volumeMounts:
            - name: config
              mountPath: /app/etc
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: payment-config
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/component: api
spec:
  selector:
    app: payment
  ports:
    - port: 8080
      targetPort: 8080
