apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  DATABASE_CONNECTION_STRING: "host=postgres port=5432 user=mall password=mall dbname=mall sslmode=disable"
  REDIS_HOST: "redis:6379"
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-db-secret
type: Opaque
stringData:
  WORKFLOWSTORE_DATABASE_CONNECTION_STRING: "host=postgres port=5432 user=mall password=mall dbname=workflow sslmode=disable"
