# syntax=docker/dockerfile:1
ARG SERVICE
ARG DEBUG=0

FROM golang:1.26-alpine AS dlv
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest

FROM alpine:3.20
ARG SERVICE
ARG DEBUG=0
RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app
COPY ${SERVICE}/bin/app ./app
COPY --from=dlv /go/bin/dlv ./dlv
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh ./app ./dlv
ENV SERVICE=${SERVICE}
ENV DEBUG=${DEBUG}
ENTRYPOINT ["/app/entrypoint.sh"]
